### ISSUE TITLE
switch --check

### ISSUE THREAD

**Issue by hamnaz** [iceland2k14/AltCrack#1]
waiting your switch --check apply inside code
thankx

**Comment by hamnaz** [comment]
Waiting your consideration at func --check. As we discus it at discord group

**Comment by hamnaz** [comment]
waiting your reply regarding this subject too

**Comment by marcelosantoto** [comment]
Hello, good night, I ask if you have to make any changes or specific configuration to run the program with the nvidia rtx 3000 series, I await your response.

**Comment by iceland2k14** [comment]
No Plan Yet
