### ISSUE TITLE
Makefile correction

### ISSUE THREAD

**Issue by hamnaz** [iceland2k14/AltCrack#4]
Correct your line
NVCCFLAGS=-std=c++11 -gencode=arch=compute_${COMPUTE_CAP},code=sm_${COMPUTE_CAP} -Xptxas="-v" -Xcompiler "${CXXFLAGS}"
--
old line is 

NVCCFLAGS=-std=c++11 -gencode=arch=compute_${COMPUTE_CAP},code=\"sm_${COMPUTE_CAP}\" -Xptxas="-v" -Xcompiler "${CXXFLAGS}"

only change 
code=\"sm_${COMPUTE_CAP}\"
to
code=sm_${COMPUTE_CAP}

**Comment by websonder** [comment]
i have change this to but still getting this error

bin/sh: 3: Syntax error: Unterminated quoted string
make[1]: *** [Makefile:9: cuda] Error 2
make[1]: Leaving directory '/home/dhl/Desktop/AltCrack-master/CudaKeySearchDevice'
make: *** [Makefile:59: dir_cudaKeySearchDevice] Error 2
root@dhl:/home/dhl/Desktop/AltCrack-master#

**Comment by hamnaz** [comment]
write your hardware details, 
gpu and installed g++ version ?

**Comment by websonder** [comment]
g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

nvcc --version
vcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

nvidia-smi

-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:01:00.0  On |                  N/A |
| 52%   72C    P2   348W / 350W |   4139MiB / 24267MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       943      G   /usr/lib/xorg/Xorg                 84MiB |
|    0   N/A  N/A      1292      G   /usr/bin/gnome-shell               28MiB |
|    0   N/A  N/A      2666      G   gnome-control-center                4MiB |
|    0   N/A  N/A     13848      G   /usr/lib/firefox/firefox            4MiB |
|    0   N/A  N/A     13872      G   /usr/lib/firefox/firefox            4MiB |
|    0   N/A  N/A     14053      G   /usr/lib/firefox/firefox            4MiB |
|    0   N/A  N/A     14096      G   /usr/lib/firefox/firefox            4MiB |
|    0   N/A  N/A     31620      G   /usr/lib/firefox/firefox            4MiB |
|    0   N/A  N/A     48048      C   ./clBitCrack                     3995MiB |
+-----------------------------------------------------------------------------+

**Comment by hamnaz** [comment]
0 N/A N/A 48048 C ./clBitCrack 3995MiB |

already running, where is problem u have ?

**Comment by websonder** [comment]
when i run ./cuBitcrack  i got invalid symbol error

**Comment by hamnaz** [comment]
wait for dev to responce for this error

**Comment by websonder** [comment]
Okay

**Comment by iceland2k14** [comment]
Thanks for trying. 
Yes i have seen issues while using the Newer Cards. Specially RTX 3090 in CUDA mode.
Unfortunately there is no current solution to this problem. I hope after version 11.2 or more changes, it might be better.
Currently, the only way is to use on them, cl version. Thanks.

**Comment by websonder** [comment]
Thanks, 
Let me Know if you found again thanks for beautiful tool
