### ISSUE TITLE
What is the input format ?

### ISSUE THREAD

**Issue by anooprh** [iceland2k14/AltCrack#6]
How do you convert a publicly available address to it's Hash160 ? For e.g one of the addresses with balance is `1FoXsj5d6Un8kEW4FEHEe1ZM2gk3eiMmqf` 

(https://www.blockchain.com/btc/address/1FoXsj5d6Un8kEW4FEHEe1ZM2gk3eiMmqf)

**Comment by iceland2k14** [comment]
Hi,
You can convert the address of any Coins into Hash160 either by code or online something like this. 
For example your address hash160 can be found by ......... https://blockchain.info/q/addresstohash/1FoXsj5d6Un8kEW4FEHEe1ZM2gk3eiMmqf
which is ....
a25eab03050480aa0cc5a3db9c4b93227467ece3
