### ISSUE TITLE
Altcoin issue

### ISSUE THREAD

**Issue by robywijaya007** [iceland2k14/AltCrack#8]
Hello Iceland , i test the program using doge coin , any peticular tricks so i can use it ? i had error 
Loading addresses from 'doge.txt'
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
Aborted (core dumped)
Please Help , 
Regards

**Comment by iceland2k14** [comment]
I think this error maybe, you are giving Dogecoin Address in the input file. You must give Hash160 file not the address.
HASH160 is the RipeMD160 hash of the SHA256 from the Pubkey.
This can be back calculated from the Dogecoin address (and for all of those Altcoin Address) by Base58decode and removing Checksum and network bytes.

**Comment by robywijaya007** [comment]
thank you for your kind reply iceland , i convert the doge address  using btcposbal converter , are they same ? 
best regards

**Comment by iceland2k14** [comment]
No idea about this converter. But if using python with library bit, you can convert entire doge_list of address into h160_list...
`h160_list = [bit.base58.b58decode_check(address)[1:].hex() for address in doge_list]`

**Comment by robywijaya007** [comment]
thank you for your kind reply iceland , now its working like charm 
regards
