### ISSUE TITLE
OpenCL.exe

### ISSUE THREAD

**Issue by sezginyildirim91** [iceland2k14/AltCrack#9]
Hello. Can you share the OpenCL compilation?

**Comment by iceland2k14** [comment]
Its here....
[https://github.com/iceland2k14/AltCrack/blob/master/x64/Release/clAltCrack.exe](https://github.com/iceland2k14/AltCrack/blob/master/x64/Release/clAltCrack.exe)

**Comment by sezginyildirim91** [comment]
> Its here....
> https://github.com/iceland2k14/AltCrack/blob/master/x64/Release/clAltCrack.exe

Thanks 💯
